# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200610_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=15),
        ),
    ]
