# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
