# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
