# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 08:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20200611_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(default=datetime.datetime.today, null=True),
        ),
    ]
