# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 18:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match1', models.CharField(default='', max_length=254)),
                ('sascore1', models.IntegerField(max_length=3)),
                ('lionsscore1', models.IntegerField(max_length=3)),
                ('submit_date', models.DateField(default=datetime.date.today, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
