# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='lionsscore1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sascore1',
            field=models.IntegerField(),
        ),
    ]
