# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20200522_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='firstpoints1',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
