# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competition_firstpoints1'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='firstpoints2',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='firstpoints3',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='firstpoints4',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='firstpoints5',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='firstpoints6',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='firstpoints7',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='firstpoints8',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], default='timezone.now', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints4',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints5',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints6',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints7',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='matchpoints8',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='competition',
            name='firstpoints1',
            field=models.CharField(choices=[('NO POINTS SCORED', 'No Points Scored'), ('HOME TEAM TRY', 'Home Team Try'), ('HOME TEAM PENALTY', 'Home Team Penalty'), ('HOME TEAM DROP GOAL', 'Home Team Drop Goal'), ('LIONS TEAM TRY', 'Lions Try'), ('LIONS PENALTY', 'Lions Penalty'), ('LIONS DROP GOAL', 'Lions Drop Goal')], max_length=20),
        ),
    ]
