# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20200528_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
