# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200518_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Woman', 'Woman'), ('Children', 'Children'), ('Souvenirs', 'Souvenirs')], default='Men', max_length=20),
        ),
    ]
