# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200519_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_qty',
        ),
    ]
